### ISSUE TITLE
Problem in MATLAB: Undefined variable

### ISSUE THREAD

**Issue by dtolis99** [prclibo/calibration-toolbox#12]
Hello,
I would like to ask about an error that has occurred. I have downloaded the code and I tried to run the demo calibration pattern. However after the images are loaded and the "### Process Images" Procedure has started it is displayed:

```
### Process Images
Camera #1: Adding photo #129...
....Matches: 83
Undefined variable "vision" or class
"vision.GeometricTransformEstimator".

Error in CameraCalibrationBase/addPhoto
(line 151)
            estimator =
            vision.GeometricTransformEstimator;

Error in CameraSystemCalibration/addPhoto
(line 102)
            photoIndex =
            obj.cameraCalibrations(cameraIndex).addPhoto(photo);

Error in main (line 107)
    obj.addPhoto(photos(i).camera,
    photos(i).image,
    num2str(photos(i).timeStamp));:
```

So, why this error is happening? I run MATLAB 2018b on Windows
Thank you in advance.

**Comment by pollyminatel** [comment]
Hi, did you manage to solve it?

**Comment by dtolis99** [comment]
> Hi, did you manage to solve it?

Hi, sorry for the delayed answer. Unfortunately I couldn't solve it.

**Comment by prclibo** [comment]
The `vision.GeometricTransformEstimator;` api seems to have changed a lot since Matlab 2012. See this link for a replacement. https://www.mathworks.com/matlabcentral/answers/521519-what-function-replaced-vision-geometrictransformestimator

**Comment by prclibo** [comment]
Fixed in https://github.com/prclibo/calibration-toolbox/commit/6e2ad28923d26f24430534f88643e721785b04d0
