### ISSUE TITLE
World scale of translation info?

### ISSUE THREAD

**Issue by antithing** [prclibo/calibration-toolbox#4]
Hi, thank you for this code, it is very useful. i just have a quick question...  In other calibration techniques using a checkerboard, the size of the squares is given, and this is used to give the scale of the translation distance between cameras.

 I have run your tools on a 5 camera system, and the layout of the cameras looks perfect, but the distance between them is much too large. Where does this scale come from? Is it the pattern size?

Thanks again!

**Comment by prclibo** [comment]
yes, scale your resulted translation by [printed size of the pattern] / [pixel size of the pattern].

**Comment by sklf** [comment]
> yes, scale your resulted translation by [printed size of the pattern] / [pixel size of the pattern].

Hello, my origin pattern size is [14040pix x 9920pix] and my printed size is [119cm x 83cm]. When I ran calibration,  I choose the pattern scale factor of 0.1. So :
1. What pixel size of the pattern should I choose,  [14040pix x 9920pix] or  [1404pix x 992pix]?
2. As you can see, 119/14040 != 83/9920, so how do I choose the right  ` [printed size of the pattern] / [pixel size of the pattern]`?
