### ISSUE TITLE
Some cameras are not connected in the calibration.

### ISSUE THREAD

**Issue by sklf** [prclibo/calibration-toolbox#8]
Hello, I tried to use your calibration-toolbox to calibrate my multi-camera system, which includes 4 Pi cameras. I make 2 neighbor cameras to take about 15~20 pictures at each time, for example, cam1 and cam2, cam2 and cam3, cam3 and cam4, cam4 and cam1. Then I ran the calibrartion code . But it showed the wrong message: "Some cameras are not connected in the calibration." I don't know the reason why it happened. Could you help me to figure it out? Thank you very much!

**Comment by prclibo** [comment]
Probably make sure both of a neighbor camera pair see sufficient pattern features.

**Comment by sklf** [comment]
> Probably make sure both of a neighbor camera pair see sufficient pattern features.

Thanks for your reply. I tried to make the pattern board closer  to the camera pairs and it seems worked well now.  Another question is that I found a parameter named 'xi' in the final result: 'obj.cameraCalibrations(1,1).camera'. But I don't know what it is used for. Could you tell me what it does?  I'm trying to convert camera params to openCV format.

**Comment by prclibo** [comment]
xi is from catadioptric camear model. Switch to pinhole camera model if you do not use it. See the paper for details:)
