### ISSUE TITLE
Camera Environment

### ISSUE THREAD

**Issue by ahsan3803** [prclibo/calibration-toolbox#9]
This tool is nice. Current multi-camera setup is like following... 
![image](https://user-images.githubusercontent.com/58796370/79818419-55829b80-83ba-11ea-874f-f95c5a2a394b.png)

If we setup multi-camera environment like below than will it be good and return same results as above setup?
![WeChat Image_20200421102227](https://user-images.githubusercontent.com/58796370/79818842-4cde9500-83bb-11ea-98c8-f057973afd7e.jpg)

**Comment by prclibo** [comment]
depends on if any two pairs of the cameras can observe enough parts of one pattern at the same time.
